name: CD-Liara
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: build
        run: |
          npm i
          npm run build
      - name: deploy to liara
        working-directory: public
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: npx @liara/cli@3 deploy --app="vajename" --api-token="$LIARA_TOKEN" --detach
